id: IC3CBB0BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T22:15:01+00:00'
last_modified: '2022-06-07T12:43:42.211584+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1042
  title: གཏེར་ཆོས། རྩ་གསུམ་གླིང་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F59E:
      image_group_id: I1PD108789
      title: ''
      total_pages: 814
      order: 1
      base_file: F59E.txt
    E766:
      image_group_id: I1PD108790
      title: ''
      total_pages: 1010
      order: 2
      base_file: E766.txt
    4F56:
      image_group_id: I1PD108791
      title: ''
      total_pages: 868
      order: 3
      base_file: 4F56.txt
    '9093':
      image_group_id: I1PD108792
      title: ''
      total_pages: 914
      order: 4
      base_file: 9093.txt
    21B3:
      image_group_id: I1PD108793
      title: ''
      total_pages: 830
      order: 5
      base_file: 21B3.txt
    1FFB:
      image_group_id: I1PD108794
      title: ''
      total_pages: 536
      order: 6
      base_file: 1FFB.txt
    493F:
      image_group_id: I1PD108795
      title: ''
      total_pages: 582
      order: 7
      base_file: 493F.txt
    '3940':
      image_group_id: I1PD108796
      title: ''
      total_pages: 704
      order: 8
      base_file: 3940.txt
    A1DD:
      image_group_id: I1PD108797
      title: ''
      total_pages: 832
      order: 9
      base_file: A1DD.txt
    4F04:
      image_group_id: I1PD108798
      title: ''
      total_pages: 972
      order: 10
      base_file: 4F04.txt
    C4E1:
      image_group_id: I1PD108799
      title: ''
      total_pages: 622
      order: 11
      base_file: C4E1.txt
    B5A9:
      image_group_id: I1PD108800
      title: ''
      total_pages: 738
      order: 12
      base_file: B5A9.txt
    C236:
      image_group_id: I1PD108801
      title: ''
      total_pages: 768
      order: 13
      base_file: C236.txt
    77E7:
      image_group_id: I1PD108802
      title: ''
      total_pages: 732
      order: 14
      base_file: 77E7.txt
    3AFA:
      image_group_id: I1PD108803
      title: ''
      total_pages: 402
      order: 15
      base_file: 3AFA.txt
    493A:
      image_group_id: I1PD108804
      title: ''
      total_pages: 576
      order: 16
      base_file: 493A.txt
    C1B7:
      image_group_id: I1PD108805
      title: ''
      total_pages: 514
      order: 17
      base_file: C1B7.txt
    7FE8:
      image_group_id: I1PD108806
      title: ''
      total_pages: 616
      order: 18
      base_file: 7FE8.txt
    CF4D:
      image_group_id: I1PD108807
      title: ''
      total_pages: 784
      order: 19
      base_file: CF4D.txt
    93AF:
      image_group_id: I1PD108808
      title: ''
      total_pages: 882
      order: 20
      base_file: 93AF.txt
    '9212':
      image_group_id: I1PD108809
      title: ''
      total_pages: 602
      order: 21
      base_file: 9212.txt
    A837:
      image_group_id: I1PD108810
      title: ''
      total_pages: 714
      order: 22
      base_file: A837.txt
    936D:
      image_group_id: I1PD108811
      title: ''
      total_pages: 706
      order: 23
      base_file: 936D.txt
    55C0:
      image_group_id: I1PD108812
      title: ''
      total_pages: 612
      order: 24
      base_file: 55C0.txt
    B14B:
      image_group_id: I1PD108813
      title: ''
      total_pages: 904
      order: 25
      base_file: B14B.txt
    DD3D:
      image_group_id: I1PD108814
      title: ''
      total_pages: 520
      order: 26
      base_file: DD3D.txt
    EB08:
      image_group_id: I1PD108815
      title: ''
      total_pages: 687
      order: 27
      base_file: EB08.txt
    E13E:
      image_group_id: I1PD108816
      title: ''
      total_pages: 665
      order: 28
      base_file: E13E.txt
    0E0B:
      image_group_id: I1PD108817
      title: ''
      total_pages: 324
      order: 29
      base_file: 0E0B.txt
    '4904':
      image_group_id: I1PD108818
      title: ''
      total_pages: 764
      order: 30
      base_file: 4904.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
