id: IC3CBB0BB
legacy_id: P000712
ocr_import_info:
  bdrc_scan_id: W4CZ1042
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T22:05:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:13:01.602350+00:00'
last_modified: 2022-09-04 02:22:15.559351
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ1042
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ1042
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆོས། རྩ་གསུམ་གླིང་པ།
  author: གནམ་ལྕགས་རྩ་གསུམ་གཏེར་བདག་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6710163206623392
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1PD108816:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108816
      total_pages: 665
      volume_number: 28
      volume_pages_bdrc_intro: 2
    order: 28
    base_file: I1PD108816.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.883739282288694
    legacy_id: v028
  I1PD108810:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108810
      total_pages: 714
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I1PD108810.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6212534248643995
    legacy_id: v022
  I1PD108808:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108808
      total_pages: 882
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I1PD108808.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7003342518920032
    legacy_id: v020
  I1PD108807:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108807
      total_pages: 784
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I1PD108807.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.7306658583324815
    legacy_id: v019
  I1PD108809:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108809
      total_pages: 602
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I1PD108809.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.682306757386924
    legacy_id: v021
  I1PD108794:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108794
      total_pages: 536
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1PD108794.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.7329397019869084
    legacy_id: v006
  I1PD108792:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108792
      total_pages: 914
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1PD108792.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6322438745657883
    legacy_id: v004
  I1PD108790:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108790
      total_pages: 1010
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD108790.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.6837079381490277
    legacy_id: v002
  I1PD108815:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108815
      total_pages: 687
      volume_number: 27
      volume_pages_bdrc_intro: 2
    order: 27
    base_file: I1PD108815.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9223293091864276
    legacy_id: v027
  I1PD108806:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108806
      total_pages: 616
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I1PD108806.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6290672727590336
    legacy_id: v018
  I1PD108818:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108818
      total_pages: 764
      volume_number: 30
      volume_pages_bdrc_intro: 2
    order: 30
    base_file: I1PD108818.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9439876934814974
    legacy_id: v030
  I1PD108817:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108817
      total_pages: 324
      volume_number: 29
      volume_pages_bdrc_intro: 2
    order: 29
    base_file: I1PD108817.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.7397995588530556
    legacy_id: v029
  I1PD108803:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108803
      total_pages: 402
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I1PD108803.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.7099004847938768
    legacy_id: v015
  I1PD108799:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108799
      total_pages: 622
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1PD108799.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.6831030622103638
    legacy_id: v011
  I1PD108805:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108805
      total_pages: 514
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I1PD108805.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.6714306535691981
    legacy_id: v017
  I1PD108791:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108791
      total_pages: 868
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD108791.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.6721746034386885
    legacy_id: v003
  I1PD108811:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108811
      total_pages: 706
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I1PD108811.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.6892694361697566
    legacy_id: v023
  I1PD108812:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108812
      total_pages: 612
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I1PD108812.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6146868774425285
    legacy_id: v024
  I1PD108797:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108797
      total_pages: 832
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1PD108797.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.619628813081802
    legacy_id: v009
  I1PD108793:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108793
      total_pages: 830
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1PD108793.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.671871030602043
    legacy_id: v005
  I1PD108802:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108802
      total_pages: 732
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1PD108802.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.7276349698225459
    legacy_id: v014
  I1PD108801:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108801
      total_pages: 768
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1PD108801.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.6624222702738353
    legacy_id: v013
  I1PD108814:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108814
      total_pages: 520
      volume_number: 26
      volume_pages_bdrc_intro: 2
    order: 26
    base_file: I1PD108814.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.679059073129368
    legacy_id: v026
  I1PD108789:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108789
      total_pages: 814
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD108789.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.7192925637051127
    legacy_id: v001
  I1PD108795:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108795
      total_pages: 582
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1PD108795.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.6606155303845617
    legacy_id: v007
  I1PD108798:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108798
      total_pages: 972
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1PD108798.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6508321000314673
    legacy_id: v010
  I1PD108813:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108813
      total_pages: 904
      volume_number: 25
      volume_pages_bdrc_intro: 2
    order: 25
    base_file: I1PD108813.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.6682680413342982
    legacy_id: v025
  I1PD108796:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108796
      total_pages: 704
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1PD108796.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.650726006226039
    legacy_id: v008
  I1PD108800:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108800
      total_pages: 738
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1PD108800.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.6836239811685876
    legacy_id: v012
  I1PD108804:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108804
      total_pages: 576
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I1PD108804.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.655667774008417
    legacy_id: v016
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
