id: P000712
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-16 16:38:25.464361
source_metadata:
  id: bdr:W4CZ1042
  title: གཏེར་ཆོས། རྩ་གསུམ་གླིང་པ།
  author: ''
  volumes:
    ad362ec0084942ed9e6ff32a37fb33d1:
      image_group_id: I1PD108789
      title: ''
      volume_number: 1
      total_pages: 814
      base_file: v001.txt
    346bc7633c1349d8aee0d877539ec475:
      image_group_id: I1PD108790
      title: ''
      volume_number: 2
      total_pages: 1010
      base_file: v002.txt
    0551b1ada3c549c38f3b701ac2b9da23:
      image_group_id: I1PD108791
      title: ''
      volume_number: 3
      total_pages: 868
      base_file: v003.txt
    c26d5c62deee4bf3b9fdf184dadc692e:
      image_group_id: I1PD108792
      title: ''
      volume_number: 4
      total_pages: 914
      base_file: v004.txt
    484f32bdd5d44eac886399c8866a40c0:
      image_group_id: I1PD108793
      title: ''
      volume_number: 5
      total_pages: 830
      base_file: v005.txt
    bdc6fee9b3304860b640c6f9071b132e:
      image_group_id: I1PD108794
      title: ''
      volume_number: 6
      total_pages: 536
      base_file: v006.txt
    9e2f456be23b45e698f150232644d873:
      image_group_id: I1PD108795
      title: ''
      volume_number: 7
      total_pages: 582
      base_file: v007.txt
    5e51e260b04543458766401d96707248:
      image_group_id: I1PD108796
      title: ''
      volume_number: 8
      total_pages: 704
      base_file: v008.txt
    c72ba8e1d31f4af780e67e08ba7550c2:
      image_group_id: I1PD108797
      title: ''
      volume_number: 9
      total_pages: 832
      base_file: v009.txt
    597be09dfbb54514863ac415392d5498:
      image_group_id: I1PD108798
      title: ''
      volume_number: 10
      total_pages: 972
      base_file: v010.txt
    390128c1395c4321825d5b9b14d2db73:
      image_group_id: I1PD108799
      title: ''
      volume_number: 11
      total_pages: 622
      base_file: v011.txt
    0033b25fd72e434a9a2d3274e551feba:
      image_group_id: I1PD108800
      title: ''
      volume_number: 12
      total_pages: 738
      base_file: v012.txt
    9867c971f6294d588c92bfacc82036e0:
      image_group_id: I1PD108801
      title: ''
      volume_number: 13
      total_pages: 768
      base_file: v013.txt
    1c8750a748344a619f8fae68f623cf5c:
      image_group_id: I1PD108802
      title: ''
      volume_number: 14
      total_pages: 732
      base_file: v014.txt
    e35a045bfb2b43e89b85fd313125b01c:
      image_group_id: I1PD108803
      title: ''
      volume_number: 15
      total_pages: 402
      base_file: v015.txt
    83eab002ea5648a4aa6cc4621c8d5cbe:
      image_group_id: I1PD108804
      title: ''
      volume_number: 16
      total_pages: 576
      base_file: v016.txt
    63173caff21042c68e2580f80952171a:
      image_group_id: I1PD108805
      title: ''
      volume_number: 17
      total_pages: 514
      base_file: v017.txt
    01adc974b0ca409387a572e299ac5618:
      image_group_id: I1PD108806
      title: ''
      volume_number: 18
      total_pages: 616
      base_file: v018.txt
    c22fd223345342b38001dba8cd842742:
      image_group_id: I1PD108807
      title: ''
      volume_number: 19
      total_pages: 784
      base_file: v019.txt
    c86591470e564d8f85d7d3f644d88de3:
      image_group_id: I1PD108808
      title: ''
      volume_number: 20
      total_pages: 882
      base_file: v020.txt
    af6bda4f20424cd2a36275d4e3337597:
      image_group_id: I1PD108809
      title: ''
      volume_number: 21
      total_pages: 602
      base_file: v021.txt
    6e042c7baee847ca98fe4ba247509a32:
      image_group_id: I1PD108810
      title: ''
      volume_number: 22
      total_pages: 714
      base_file: v022.txt
    9d960eacd343484c8c8a576178d560e4:
      image_group_id: I1PD108811
      title: ''
      volume_number: 23
      total_pages: 706
      base_file: v023.txt
    ff0227fb00cc4371b228af9884367cd2:
      image_group_id: I1PD108812
      title: ''
      volume_number: 24
      total_pages: 612
      base_file: v024.txt
    6d869fb9ccdd4fc8a133134c7c2e3a8b:
      image_group_id: I1PD108813
      title: ''
      volume_number: 25
      total_pages: 904
      base_file: v025.txt
    73fb43b8299d4f759ae73421f0b97db3:
      image_group_id: I1PD108814
      title: ''
      volume_number: 26
      total_pages: 520
      base_file: v026.txt
    27a224de92294615b60574cbbddb02aa:
      image_group_id: I1PD108815
      title: ''
      volume_number: 27
      total_pages: 687
      base_file: v027.txt
    259f6bdaabe04583ada5c870f80af2a2:
      image_group_id: I1PD108816
      title: ''
      volume_number: 28
      total_pages: 665
      base_file: v028.txt
    cf49a23af32f41b5b73c4d16f233b75e:
      image_group_id: I1PD108817
      title: ''
      volume_number: 29
      total_pages: 324
      base_file: v029.txt
    9264cc0ca4b44718b31059cae7de61d6:
      image_group_id: I1PD108818
      title: ''
      volume_number: 30
      total_pages: 764
      base_file: v030.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
